
name: CI_tf2

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
      - 'tf2/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'tf2/**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      SSH_KEY: ${{secrets.SSH_KEY}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - run: 'echo "$SSH_KEY" > ../id_rsa'
        shell: bash
        env:
          SSH_KEY: ${{secrets.SSH_KEY}}
      - run: 'echo "$SSH_KEY_PUB" > ../id_rsa.pub'
        shell: bash
        env:
          SSH_KEY_PUB: ${{secrets.SSH_KEY_PUB}}
      - run: go test -v -timeout 15m -run TestTf2
        working-directory: test
